// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd4oOYQym9nUjMtJtxngj8pumgy8B0A3k',
    appId: '1:722917557653:web:08395475178daf85eba29c',
    messagingSenderId: '722917557653',
    projectId: 'easyorder-50ad2',
    authDomain: 'easyorder-50ad2.firebaseapp.com',
    storageBucket: 'easyorder-50ad2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYd4_Iv4NUzijaYH_JlWPzH2e1hj5ya2E',
    appId: '1:722917557653:android:4c730964d097bb15eba29c',
    messagingSenderId: '722917557653',
    projectId: 'easyorder-50ad2',
    storageBucket: 'easyorder-50ad2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvaX79EWVy2m-8bhET7q96ljjp2E3mI1Q',
    appId: '1:722917557653:ios:608c766d0e238cdaeba29c',
    messagingSenderId: '722917557653',
    projectId: 'easyorder-50ad2',
    storageBucket: 'easyorder-50ad2.appspot.com',
    iosBundleId: 'com.example.easyorder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvaX79EWVy2m-8bhET7q96ljjp2E3mI1Q',
    appId: '1:722917557653:ios:608c766d0e238cdaeba29c',
    messagingSenderId: '722917557653',
    projectId: 'easyorder-50ad2',
    storageBucket: 'easyorder-50ad2.appspot.com',
    iosBundleId: 'com.example.easyorder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd4oOYQym9nUjMtJtxngj8pumgy8B0A3k',
    appId: '1:722917557653:web:fe4e550451935e94eba29c',
    messagingSenderId: '722917557653',
    projectId: 'easyorder-50ad2',
    authDomain: 'easyorder-50ad2.firebaseapp.com',
    storageBucket: 'easyorder-50ad2.appspot.com',
  );
}
